name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  my-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - name: List current folders
      run : node first_task_1.js 1 2 3 4 5 -7 2 12
