name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  my-testing:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - name: Chage permissions
      run : chmod a+x bin/bash
      
    - name: Make tests
      run : npm test
